export enum AvailableRoles {
  ADMIN = "ADMIN",
  USER_READ = "USER_READ",
  USER_WRITE = "USER_WRITE",
  USER_DELETE = "USER_DELETE",
  RH_READ = "USER_READ",
  RH_WRITE = "RH_WRITE",
  RH_DELETE = "RH_DELETE",
}
